# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TuiTodo < Formula
  desc "A feature-rich terminal-based todo application built with Go.
Organize tasks with tags, priorities, and due dates without leaving your terminal.
"
  homepage "https://github.com/martijnspitter/tui-todo"
  version "0.0.29"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/martijnspitter/tui-todo/releases/download/v0.0.29/tui-todo_Darwin_x86_64.tar.gz"
      sha256 "56f5b18f6dad1c44d800ad078e272d186db011396349f2ff30adde7a82c63d61"

      def install
        bin.install "tui-todo" => "todo"  # This renames the binary when installing
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/martijnspitter/tui-todo/releases/download/v0.0.29/tui-todo_Darwin_arm64.tar.gz"
      sha256 "4da6d9072a22ac9488ec73b249a6b0bd5884b397836ada48c0c4dde4a74642cc"

      def install
        bin.install "tui-todo" => "todo"  # This renames the binary when installing
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/martijnspitter/tui-todo/releases/download/v0.0.29/tui-todo_Linux_x86_64.tar.gz"
      sha256 "7ca6e5a77f98112fbbb493b95b4c4d575c9b9c1f5aeeaae8ac49eb5586776a48"
      def install
        bin.install "tui-todo" => "todo"  # This renames the binary when installing
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/martijnspitter/tui-todo/releases/download/v0.0.29/tui-todo_Linux_arm64.tar.gz"
      sha256 "3b76dd68ad1da92135d93616dc262ed42162957105b4b6415600a99c8791deb2"
      def install
        bin.install "tui-todo" => "todo"  # This renames the binary when installing
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing TUI Todo!
      Run 'todo' to start the application.
    EOS
  end

  test do
    system "#{bin}/todo", "--version"
  end
end
