# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TuiTodo < Formula
  desc "Terminal-based todo application with rich features"
  homepage "https://github.com/martijnspitter/tui-todo"
  version "0.0.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/martijnspitter/tui-todo/releases/download/v0.0.17/tui-todo_Darwin_x86_64.tar.gz"
      sha256 "166037d53b8b7c1194a128dd83ff962c9c0fe4f23e12919327397190fd5db9d9"

      def install
        bin.install "tui-todo" => "todo"  # This renames the binary when installing
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/martijnspitter/tui-todo/releases/download/v0.0.17/tui-todo_Darwin_arm64.tar.gz"
      sha256 "aa387dcea3557a319a4e7449e337e79ec3ee22030ecf7ee1626aef53fecbc8f7"

      def install
        bin.install "tui-todo" => "todo"  # This renames the binary when installing
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/martijnspitter/tui-todo/releases/download/v0.0.17/tui-todo_Linux_x86_64.tar.gz"
        sha256 "439906db309f2406d0b11fee43dcf6e7f2709681cd2cbb0e2bc9d8cb422ba8ba"

        def install
          bin.install "tui-todo" => "todo"  # This renames the binary when installing
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/martijnspitter/tui-todo/releases/download/v0.0.17/tui-todo_Linux_arm64.tar.gz"
        sha256 "0220f0eed936a423b6b1895bdced3709e43d55ea50a4f8b29ee0c338acaa3b2d"

        def install
          bin.install "tui-todo" => "todo"  # This renames the binary when installing
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing TUI Todo!
      Run 'todo' to start the application.
    EOS
  end

  test do
    system "#{bin}/todo", "--version"
  end
end
